runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(?:js|ico|css|svg|png))$
  static_files: \1
  upload: .*\.(?:js|ico|css|svg|png)

- url: /.*
  static_files: index.html
  upload: index.html
